image: microsoft/dotnet:latest

stages:
  - build

before_script:
  - 'apt-get update'
  - 'apt-get install -y nuget'
  - 'nuget restore ner-number-generator.sln'

build:
 stage: build
 script:
  - 'dotnet publish -c Release -o out'
 only:
   - master