image: mono:4.4.0.182

build:
  stage: build
  script:
    - nuget restore ner-number-generator.sln
    - MONO_IOMAP=case xbuild /t:Build /p:Configuration="Release" /p:Platform="Any CPU" ner-number-generator.sln