image: mono:4.4.0.182

stages:
  - build

before_script:
  - 'apt-get install -y nuget'
  - 'nuget restore ner-number-generator.sln'

build:
 stage: build
 script:
  - 'msbuild ner-number-generator.sln /t:ReBuild /p:Configuration=Release;Platform="Any CPU"'
  - 'nuget pack "ner-number-generator/ner-number-generator.csproj" -IncludeReferencedProjects -Build -Properties Configuration=Release -Version 0.0.1.%CI_BUILD_ID%'
  - 'nuget push \*.nupkg %NugetAPIKey% -Source %NugetSource%'
 only:
   - master