image: microsoft/dotnet:latest

stages:
  - Debug
  - Release

before_script:
  - 'dotnet restore'

build-debug:
 stage: Debug
 script:
  - 'dotnet run'
 only:
   - master

build-release:
 stage: Release
 script:
  - 'dotnet publish -c Release -o out'
 artifacts:
  paths:
   - out/
 only:
  - master